{
  "hash": "0aaa13a38e69c39ceb0617d15ceb6eba",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Built-in datasets\"\nguide-section: \"Getting started\"\nbread-crumbs: false\n---\n\n\n\nWhittaker ships with 10 synthetic datasets covering a range of response families and modeling\nscenarios. They are generated with fixed random seeds, so they are fully reproducible without\ninternet access or optional dependencies. Use them for quick demonstrations, testing, and learning.\n\n## Listing available datasets\n\n`list_datasets()` returns metadata for every built-in dataset:\n\n::: {#68dc0a83 .cell execution_count=2}\n``` {.python .cell-code}\nimport whittaker as wk\n\nfor ds in wk.list_datasets():\n    print(f\"{ds['name']:>14}  {ds['family']:<12}  {ds['description']}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        mcycle  Gaussian      Simulated motorcycle-crash accelerometer data (n=133).\n           co2  Gaussian      Synthetic monthly atmospheric CO2 concentrations (n=504, 1958–1999).\n          fish  Poisson       Synthetic fish-count survey data (n=300).\n        credit  Binomial      Synthetic credit-default dataset (n=1000).\n         wages  Gamma         Synthetic worker-earnings dataset (n=800).\n   proportions  Beta          Synthetic seed-germination dataset (n=400).\n         meuse  Gaussian      Synthetic river-bank heavy-metals dataset (n=155).\n      survival  CoxPH         Synthetic clinical-trial survival dataset (n=250).\n       abalone  Gaussian      Synthetic abalone morphology dataset (n=500).\n       climate  GaussianLS    Synthetic climate station dataset (n=600).\n```\n:::\n:::\n\n\nEach entry includes the dataset `name`, a short `description`, the intended response `family`,\nthe `variables` it contains, and a `note` about what modeling scenario it illustrates.\n\n## Loading a dataset\n\n`load_dataset()` returns a column-oriented dictionary that can be passed directly to `GAM.fit()`:\n\n::: {#d7c70627 .cell execution_count=3}\n``` {.python .cell-code}\ndata = wk.load_dataset(\"mcycle\")\n\nprint(f\"Type: {type(data)}\")\nprint(f\"Keys: {list(data.keys())}\")\nprint(f\"Observations: {len(data['times'])}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nType: <class 'dict'>\nKeys: ['times', 'accel']\nObservations: 133\n```\n:::\n:::\n\n\n::: {#e0bdd8c8 .cell execution_count=4}\n``` {.python .cell-code}\nmodel = wk.GAM(\"accel ~ s(times)\").fit(data)\nmodel.summary()\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```\nGAM fit summary\n============================================================\nFormula:    accel ~ s(times)\nFamily:     Gaussian(link='identity')\nInference:  GCV\nObservations: 133\nCoefficients: 10\n\nParametric coefficients:\n  Term                       Estimate    Std.Err    t value    p-value\n  ------------------------ ---------- ---------- ---------- ----------\n  (Intercept)                -45.6924     1.8364    -24.882    < 1e-16\n\nApproximate significance of smooth terms:\n  Term                        EDF Ref.df     Chi.sq    p-value\n  ------------------------ ------ ------ ---------- ----------\n  s(times)                   7.92      8    663.396    < 1e-16\n\nTotal EDF:  8.92\nScale est:  448.517253\nDeviance:   55653.7152\nNull dev:   357878.4929\nDev. expl:  84.4%\nGCV score:  480.746119\nAIC:        1198.44\nBIC:        1224.22\n```\n:::\n:::\n\n\n### Loading as a DataFrame\n\nPass `as_frame=True` to get a pandas DataFrame instead (requires pandas):\n\n::: {#ccf54d3d .cell execution_count=5}\n``` {.python .cell-code}\ndf = wk.load_dataset(\"wages\", as_frame=True)\ndf.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```{=html}\n<div id=\"gd-tbl-d828d22c\" class=\"gd-tbl-preview\" style=\"padding-left: 0px; overflow-x: auto; overflow-y: hidden; width: 100%; max-width: 100%; margin-bottom: 1em;\">\n<style>\n@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600&display=swap');\n#gd-tbl-d828d22c .gt_table {\n  display: table;\n  border-collapse: collapse;\n  table-layout: fixed;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n}\n#gd-tbl-d828d22c .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-d828d22c .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n#gd-tbl-d828d22c .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n#gd-tbl-d828d22c .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n#gd-tbl-d828d22c .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-right-style: none;\n}\n#gd-tbl-d828d22c .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #F2F2F2;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #F2F2F2;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n#gd-tbl-d828d22c .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n}\n#gd-tbl-d828d22c .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #E9E9E9;\n  border-left-style: solid;\n  border-left-width: 1px;\n  border-left-color: #E9E9E9;\n  border-right-style: solid;\n  border-right-width: 1px;\n  border-right-color: #E9E9E9;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n#gd-tbl-d828d22c .gt_left { text-align: left; }\n#gd-tbl-d828d22c .gt_center { text-align: center; }\n#gd-tbl-d828d22c .gt_right { text-align: right; font-variant-numeric: tabular-nums; }\n#gd-tbl-d828d22c .gt_font_normal { font-weight: normal; }\n#gd-tbl-d828d22c .gt_font_bold { font-weight: bold; }\n#gd-tbl-d828d22c .gt_font_italic { font-style: italic; }\n#gd-tbl-d828d22c .gt_striped { background-color: rgba(128,128,128,0.05); }\n#gd-tbl-d828d22c .gt_from_md > :first-child { margin-top: 0; }\n#gd-tbl-d828d22c .gt_from_md > :last-child { margin-bottom: 0; }\n/* Data cell font */\n#gd-tbl-d828d22c .gt_table_body .gt_row {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 14px;\n}\n/* Column label font */\n#gd-tbl-d828d22c .gt_col_heading {\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  color: #333333;\n}\n/* Row number styling */\n#gd-tbl-d828d22c .gd-tbl-rownum {\n  color: gray;\n  font-family: 'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 10px;\n  border-right: 2px solid rgba(102, 153, 204, 0.5) !important;\n  text-align: right;\n  padding-right: 6px;\n  white-space: nowrap;\n}\n/* Head/tail divider */\n#gd-tbl-d828d22c tr.gd-tbl-divider td,\n#gd-tbl-d828d22c tr.gd-tbl-divider th {\n  border-bottom: 2px solid rgba(102, 153, 204, 0.5);\n}\n/* Missing values */\n#gd-tbl-d828d22c .gd-tbl-missing {\n  color: #B22222 !important;\n  background-color: rgba(255, 193, 193, 0.35);\n}\n/* Column label sub-elements */\n#gd-tbl-d828d22c .gd-tbl-colname {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-bottom: 0;\n  margin-bottom: 0;\n}\n#gd-tbl-d828d22c .gd-tbl-dtype {\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  padding-top: 0;\n  margin-top: 0;\n  color: #666666;\n}\n/* Header badge styling */\n#gd-tbl-d828d22c .gd-tbl-badge {\n  display: inline-block;\n  padding: 2px 10px;\n  font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;\n  font-size: 10px;\n  font-weight: bold;\n  text-transform: uppercase;\n  position: inherit;\n}\n#gd-tbl-d828d22c .gd-tbl-badge-rows-label {\n  background-color: #eecbff;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: 5px;\n}\n#gd-tbl-d828d22c .gd-tbl-badge-rows-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #eecbff;\n  margin-left: -4px;\n  margin-right: 3px;\n}\n#gd-tbl-d828d22c .gd-tbl-badge-cols-label {\n  background-color: #BDE7B4;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n}\n#gd-tbl-d828d22c .gd-tbl-badge-cols-value {\n  background-color: transparent;\n  color: #333333;\n  border: 1px solid #BDE7B4;\n  margin-left: -4px;\n}\n/* Dark mode */\nbody.quarto-dark #gd-tbl-d828d22c .gt_table,\nhtml.quarto-dark #gd-tbl-d828d22c .gt_table,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d828d22c .gt_table {\n  background-color: #1a1a2e;\n  color: #e0e0e0;\n  border-top-color: #555;\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-d828d22c .gt_heading,\nhtml.quarto-dark #gd-tbl-d828d22c .gt_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d828d22c .gt_heading {\n  background-color: #1a1a2e;\n  border-bottom-color: #1a1a2e;\n}\nbody.quarto-dark #gd-tbl-d828d22c .gt_title,\nhtml.quarto-dark #gd-tbl-d828d22c .gt_title,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d828d22c .gt_title {\n  color: #e0e0e0;\n}\nbody.quarto-dark #gd-tbl-d828d22c .gt_subtitle,\nhtml.quarto-dark #gd-tbl-d828d22c .gt_subtitle,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d828d22c .gt_subtitle {\n  color: #b0b0b0;\n}\nbody.quarto-dark #gd-tbl-d828d22c .gt_col_headings,\nhtml.quarto-dark #gd-tbl-d828d22c .gt_col_headings,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d828d22c .gt_col_headings {\n  border-top-color: #444;\n  border-bottom-color: #444;\n}\nbody.quarto-dark #gd-tbl-d828d22c .gt_col_heading,\nhtml.quarto-dark #gd-tbl-d828d22c .gt_col_heading,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d828d22c .gt_col_heading {\n  color: #b0b0b0;\n  background-color: #1a1a2e;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-d828d22c .gt_table_body,\nhtml.quarto-dark #gd-tbl-d828d22c .gt_table_body,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d828d22c .gt_table_body {\n  border-top-color: #444;\n}\nbody.quarto-dark #gd-tbl-d828d22c .gt_table_body .gt_row,\nhtml.quarto-dark #gd-tbl-d828d22c .gt_table_body .gt_row,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d828d22c .gt_table_body .gt_row {\n  color: #d0d0d0;\n  border-top-color: #4b4b4b;\n  border-bottom-color: #4b4b4b;\n  border-left-color: #333;\n  border-right-color: #333;\n}\nbody.quarto-dark #gd-tbl-d828d22c .gd-tbl-rownum,\nhtml.quarto-dark #gd-tbl-d828d22c .gd-tbl-rownum,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d828d22c .gd-tbl-rownum {\n  color: #888;\n  border-right-color: rgba(102, 153, 204, 0.4) !important;\n}\nbody.quarto-dark #gd-tbl-d828d22c .gd-tbl-missing,\nhtml.quarto-dark #gd-tbl-d828d22c .gd-tbl-missing,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d828d22c .gd-tbl-missing {\n  color: #ff6b6b !important;\n  background-color: rgba(60, 17, 24, 0.2);\n}\nbody.quarto-dark #gd-tbl-d828d22c .gd-tbl-dtype,\nhtml.quarto-dark #gd-tbl-d828d22c .gd-tbl-dtype,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d828d22c .gd-tbl-dtype {\n  color: #888;\n}\nbody.quarto-dark #gd-tbl-d828d22c .gt_bottom_border,\nhtml.quarto-dark #gd-tbl-d828d22c .gt_bottom_border,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d828d22c .gt_bottom_border {\n  border-bottom-color: #555;\n}\nbody.quarto-dark #gd-tbl-d828d22c .gd-tbl-badge-rows-label,\nhtml.quarto-dark #gd-tbl-d828d22c .gd-tbl-badge-rows-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d828d22c .gd-tbl-badge-rows-label {\n  background-color: #3d2a4d;\n  border-color: #3d2a4d;\n  color: #e0c0ff;\n}\nbody.quarto-dark #gd-tbl-d828d22c .gd-tbl-badge-rows-value,\nhtml.quarto-dark #gd-tbl-d828d22c .gd-tbl-badge-rows-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d828d22c .gd-tbl-badge-rows-value {\n  border-color: #3d2a4d;\n  color: #d0b0e0;\n}\nbody.quarto-dark #gd-tbl-d828d22c .gd-tbl-badge-cols-label,\nhtml.quarto-dark #gd-tbl-d828d22c .gd-tbl-badge-cols-label,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d828d22c .gd-tbl-badge-cols-label {\n  background-color: #2a4d2a;\n  border-color: #2a4d2a;\n  color: #b0e0b0;\n}\nbody.quarto-dark #gd-tbl-d828d22c .gd-tbl-badge-cols-value,\nhtml.quarto-dark #gd-tbl-d828d22c .gd-tbl-badge-cols-value,\n:root[data-bs-theme=\"dark\"] #gd-tbl-d828d22c .gd-tbl-badge-cols-value {\n  border-color: #2a4d2a;\n  color: #a0d0a0;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"true\" data-quarto-bootstrap=\"false\">\n<colgroup>\n<col style=\"width: 35px\"/>\n<col style=\"width: 155px\"/>\n<col style=\"width: 155px\"/>\n<col style=\"width: 155px\"/>\n</colgroup>\n<thead>\n<tr class=\"gt_heading\"><td class=\"gt_heading gt_title gt_font_normal\" colspan=\"4\"><div style=\"padding-top: 0; padding-bottom: 7px;\"><span class=\"gd-tbl-badge\" style=\"background-color: #150458; color: #FFFFFF; border: 1px solid #150458; margin-right: 8px;\">Pandas</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-label\">Rows</span><span class=\"gd-tbl-badge gd-tbl-badge-rows-value\">5</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-label\">Columns</span><span class=\"gd-tbl-badge gd-tbl-badge-cols-value\">3</span></div></td></tr>\n<tr class=\"gt_col_headings\">\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"age\"><div><div class=\"gd-tbl-colname\">age</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"experience\"><div><div class=\"gd-tbl-colname\">experience</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n<th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"wage\"><div><div class=\"gd-tbl-colname\">wage</div><div class=\"gd-tbl-dtype\"><em>f64</em></div></div></th>\n</tr>\n</thead>\n<tbody class=\"gt_table_body\">\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">0</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 155px;\">62.3236369619</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 155px;\">9.21681747511</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 155px;\">80.2312228265</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">1</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 155px;\">42.0323949823</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 155px;\">2.48784091836</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 155px;\">40.0241886358</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">2</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 155px;\">63.8834541683</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 155px;\">7.2519118615</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 155px;\">60.2928515793</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">3</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 155px;\">21.7992931231</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 155px;\">3.79929312309</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 155px;\">20.2329400441</td>\n</tr>\n<tr>\n<td class=\"gt_row gt_right gd-tbl-rownum\">4</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 155px;\">46.5457241038</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 155px;\">1.73811889414</td>\n<td class=\"gt_row gt_right\" style=\"max-width: 155px;\">62.3832136627</td>\n</tr>\n</tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## Dataset catalog\n\n### mcycle — Gaussian, heteroscedastic\n\nSimulated motorcycle-crash accelerometer data (n=133). Head acceleration measured at various times\nafter impact. Strongly non-linear and heteroscedastic — a standard stress test for smoothing.\n\n::: {#62bc2443 .cell execution_count=6}\n``` {.python .cell-code}\ndata = wk.load_dataset(\"mcycle\")\nmodel = wk.GAM(\"accel ~ s(times)\").fit(data)\ngof = model.goodness_of_fit()\nprint(f\"EDF: {gof.edf_total:.1f}, Dev. explained: {gof.deviance_explained:.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEDF: 8.9, Dev. explained: 84.4%\n```\n:::\n:::\n\n\n### co2 — Gaussian, trend + seasonal\n\nSynthetic monthly CO2 concentrations (n=504, 1958–1999) with a rising trend and annual cycle. Good\nfor cyclic smooths and additive decomposition.\n\n::: {#5a3adb24 .cell execution_count=7}\n``` {.python .cell-code}\ndata = wk.load_dataset(\"co2\")\nmodel = wk.GAM(\"co2 ~ s(t) + s(month, bs='cc', k=12)\").fit(data, method=\"REML\")\ngof = model.goodness_of_fit()\nprint(f\"EDF: {gof.edf_total:.1f}, Dev. explained: {gof.deviance_explained:.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEDF: 16.5, Dev. explained: 100.0%\n```\n:::\n:::\n\n\n### fish — Poisson counts\n\nFish-abundance survey (n=300) with a hump-shaped temperature effect and a linear depth effect.\n\n::: {#e25431ac .cell execution_count=8}\n``` {.python .cell-code}\nfrom whittaker.families.poisson import Poisson\n\ndata = wk.load_dataset(\"fish\")\nmodel = wk.GAM(\"count ~ s(temperature) + s(depth)\", family=Poisson()).fit(data)\ngof = model.goodness_of_fit()\nprint(f\"EDF: {gof.edf_total:.1f}, Dev. explained: {gof.deviance_explained:.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEDF: 7.0, Dev. explained: 62.0%\n```\n:::\n:::\n\n\n### credit — Binomial (binary)\n\nCredit-default dataset (n=1000) with smooth effects of income and debt ratio on default probability.\n\n::: {#2c23ac05 .cell execution_count=9}\n``` {.python .cell-code}\nfrom whittaker.families.binomial import Binomial\n\ndata = wk.load_dataset(\"credit\")\nmodel = wk.GAM(\"default ~ s(income) + s(debt_ratio) + s(age)\", family=Binomial()).fit(data)\ngof = model.goodness_of_fit()\nprint(f\"EDF: {gof.edf_total:.1f}, Dev. explained: {gof.deviance_explained:.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEDF: 8.1, Dev. explained: 16.7%\n```\n:::\n:::\n\n\n### wages — Gamma\n\nWorker-earnings dataset (n=800) with log-wages shaped by smooth age and experience effects.\n\n::: {#3e04df91 .cell execution_count=10}\n``` {.python .cell-code}\nfrom whittaker.families.gamma import Gamma\n\ndata = wk.load_dataset(\"wages\")\nmodel = wk.GAM(\"wage ~ s(age) + s(experience)\", family=Gamma()).fit(data)\ngof = model.goodness_of_fit()\nprint(f\"EDF: {gof.edf_total:.1f}, Dev. explained: {gof.deviance_explained:.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEDF: 7.1, Dev. explained: 78.2%\n```\n:::\n:::\n\n\n### proportions — Beta\n\nSeed-germination dataset (n=400) with a bounded `[0, 1]` response and a non-linear temperature\noptimum.\n\n::: {#e1a98c72 .cell execution_count=11}\n``` {.python .cell-code}\nfrom whittaker.families.beta import Beta\n\ndata = wk.load_dataset(\"proportions\")\nmodel = wk.GAM(\"germination_rate ~ s(temperature) + s(water)\", family=Beta()).fit(data)\ngof = model.goodness_of_fit()\nprint(f\"EDF: {gof.edf_total:.1f}, Dev. explained: {gof.deviance_explained:.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEDF: 7.8, Dev. explained: 65.5%\n```\n:::\n:::\n\n\n### meuse — Gaussian, spatial\n\nRiver-bank heavy-metals dataset (n=155) with map coordinates. Log(zinc) decreases with distance\nfrom the river. Good for 2D spatial smooths.\n\n::: {#c23ee436 .cell execution_count=12}\n``` {.python .cell-code}\nimport numpy as np\n\ndata = wk.load_dataset(\"meuse\")\ndata[\"log_zinc\"] = np.log(data[\"zinc\"])\nmodel = wk.GAM(\"log_zinc ~ s(x, y) + s(dist)\").fit(data, method=\"REML\")\ngof = model.goodness_of_fit()\nprint(f\"EDF: {gof.edf_total:.1f}, Dev. explained: {gof.deviance_explained:.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEDF: 3.0, Dev. explained: 61.8%\n```\n:::\n:::\n\n\n### survival — Cox PH\n\nClinical-trial survival dataset (n=250) with a smooth age effect and a binary treatment arm.\nApproximately 30% censored.\n\n::: {#f5a38697 .cell execution_count=13}\n``` {.python .cell-code}\nfrom whittaker.families.cox_ph import CoxPH\n\ndata = wk.load_dataset(\"survival\")\nmodel = wk.GAM(\"time ~ s(age) + treatment\", family=CoxPH(status=\"event\")).fit(data)\nprint(f\"EDF: {model.goodness_of_fit().edf_total:.1f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEDF: 3.1\n```\n:::\n:::\n\n\n### abalone — Gaussian, multi-predictor\n\nAbalone morphology dataset (n=500) with four predictors and a ring count response. Good for\ntensor products and multi-term additive models.\n\n::: {#b6a4a5c6 .cell execution_count=14}\n``` {.python .cell-code}\ndata = wk.load_dataset(\"abalone\")\nmodel = wk.GAM(\"rings ~ s(length) + s(shucked_weight)\").fit(data)\ngof = model.goodness_of_fit()\nprint(f\"EDF: {gof.edf_total:.1f}, Dev. explained: {gof.deviance_explained:.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEDF: 11.4, Dev. explained: 82.7%\n```\n:::\n:::\n\n\n### climate — GaussianLS (location-scale)\n\nClimate station dataset (n=600) where both the mean and variance of temperature depend on altitude\nand latitude. Designed for GAMLSS location-scale modeling.\n\n::: {#6a6b5f36 .cell execution_count=15}\n``` {.python .cell-code}\ndata = wk.load_dataset(\"climate\")\nmodel = wk.GAM(\"temperature ~ s(altitude) + s(latitude) + s(month, bs='cc', k=12)\").fit(\n    data, method=\"REML\"\n)\ngof = model.goodness_of_fit()\nprint(f\"EDF: {gof.edf_total:.1f}, Dev. explained: {gof.deviance_explained:.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEDF: 9.5, Dev. explained: -19.9%\n```\n:::\n:::\n\n\n::: {.callout-tip}\n## GAMLSS with the climate dataset\n\nFor the full location-scale analysis, see [Distributional regression (GAMLSS)](gamlss.qmd),\nwhich models both the mean and variance as smooth functions of the predictors.\n:::\n\n## Where to go next\n\n- **[Quick start](quick-start.qmd)**: fitting your first model.\n- **[Response families](families.qmd)**: choosing the right family for your data.\n- **[Data input](data-input.qmd)**: using your own data with pandas, polars, or pyarrow.\n\n",
    "supporting": [
      "datasets_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}